### ISSUE TITLE
About MTTPPN[1:0]

### ISSUE THREAD

**Issue by jay890829** [riscv/riscv-smmtt#13]
I would like to know why MTTPPN[1:0] should always read as 0.
Please explain it to me, thanks.

**Comment by rsahita** [comment]
apologies for the delay in the response @jay890829 

So, the MTTPPN refers to an MTTL3 table or an MTTL2 table based on physical address width and it is naturally aligned to that sized byte boundary. Since the smallest MTT entry sizes in those tables are 32 bit entries (4 byte stride), the lowest two bits of the physical page number (MTTPPN) in mttp are always read as zeros.
